apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oeh7qv99z-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oeh7qv99z-java-quarkus 
  name: oeh7qv99z-java-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oeh7qv99z-java-quarkus 
